### ISSUE TITLE
send_a_frame

### ISSUE THREAD

**Issue by allenhaozi** [caosiyang/websocket#1]
connection.cpp 
send_a_frame function
the function of bufferevent_write return value is 0 or -1
fb->len is the real data length

so the return value always is -1

**Comment by caosiyang** [comment]
这是个bug，当时没有用到它的返回值，所以也没有发现。

//send a frame
inline int32_t send_a_frame(ws_conn_t *conn, const frame_buffer_t *fb) {
	return bufferevent_write(conn->bev, fb->data, fb->len);
}
